sudo: required

services:
  - docker

language: scala

scala:
  - 2.12.3

script:
  - sbt clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sh .travis/deploy_dockerhub.sh
